data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

def solve():
    split_data = [list(i) for i in data.split("\n")]
    counter = 0

    for x, line in enumerate(split_data[1:], 1):
        for y, char in enumerate(line):
            if char == ".":
                if split_data[x-1][y] == "S":
                    line[y] = "|"
                elif split_data[x-1][y] == "|":
                    line[y] = "|"
            elif char == "^":
                if split_data[x-1][y] == "S" or split_data[x-1][y] == "|":
                    counter += 1
                    if split_data[x][y-1] == ".":
                        split_data[x][y-1] = "|"

                    if split_data[x][y+1] == ".":
                        split_data[x][y+1] = "|"

    print("\n".join(["".join(i) for i in split_data]))
    print(counter)

solve()

